<a href="https://colab.research.google.com/github/ziadelidrissi5-ai/TDclustering-/blob/main/ClusteringCardCustomers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Credit Card Customer Clustering**




# <div class="header1">1. | Introduction </div>

## <div class="header2"> Dataset Problems</div>
<div class="explain-box">
    The dataset that will be used contains the <b>usage behavior of around 9000 credit card users</b> for the last six months. It is required to <mark><b>group credit card customers into several groups according to customer behavior</b></mark> to get an <b>effective and efficient credit card marketing strategy</b>.
</div>

## <div class="header2"> Notebook Objectives</div>
<div class="explain-box">
    This notebook <b>aims</b> to:
    <ul>
        <li><b>Perform dataset exploration</b> using various types of data visualization.</li>
        <li><b>Perform data preprocessing</b> before using models.</li>
        <li><b>Grouping customers into clusters</b> using various clustering models.</li>
        <li><b>Perform interpretation and analysis of the groups (profiling)</b> that have been created.</li>
        <li><b>Provide marketing suggestions</b> based on profiling results and analysis conducted.</li>
    </ul>
</div>

## <div class="header2"> Clustering Models</div>
<div class="explain-box">
    The <b>clustering models</b> used in this notebook are:
    <ol>
        <li><b>Partition based (K-Means)</b>,</li>
        <li><b>Density based (DBSCAN)</b>, and</li>
        <li><b>Hierarchical Clustering (Agglomerative)</b>.</li>
    </ol>
</div>

## <div class="header2">🧾 Dataset Description</div>
<div class="explain-box">
    The following is the <b>structure of the dataset</b>.<br>
    
<table style="font-family: Merriweather; font-weight: 300; font-size: 12px; text-align: left; padding: 8px; border-collapse: collapse; width: 100%;">
  <thead>
    <tr>
      <th style="font-family: Merriweather; font-weight: 900; text-align: center; font-size: 14px; background-color: #FFCC00">Variable Name</th>
      <th style="font-family: Merriweather; font-weight: 900; text-align: center; font-size: 14px; background-color: #FFCC00">Description</th>
      <th style="font-family: Merriweather; font-weight: 900; text-align: center; font-size: 14px; background-color: #FFCC00">Sample Data</th>
    </tr>
  </thead>
  <tbody>
      <tr>
          <td>CUST_ID</td>
          <td>Credit card holder ID</td>
          <td>C10001; C10002; ...</td>
      </tr>
      <tr>
          <td>BALANCE</td>
          <td>Remaining account balance available for purchases</td>
          <td>40.900749; 3202.467416; ...</td>
      </tr>
      <tr>
          <td>BALANCE_FREQUENCY</td>
          <td>Balance update frequency (between 0 and 1)<br><br>1 = frequently updated<br>0 = not frequently updated</td>
          <td>0.818182; 0.909091; ...</td>
      </tr>
      <tr>
          <td>PURCHASES</td>
          <td>Account purchases amount</td>
          <td>95.4; 773.17; ...</td>
      </tr>
      <tr>
          <td>ONEOFF_PURCHASES</td>
          <td>Maximum purchase amount in single transaction</td>
          <td>1499; 16; ...</td>
      </tr>
      <tr>
          <td>INSTALLMENTS_PURCHASES</td>
          <td>Amount purchase in installment</td>
          <td>95.4; 1333.28; ...</td>
      </tr>
      <tr>
          <td>CASH_ADVANCE</td>
          <td>The user's advance payment in cash</td>
          <td>6442.945483; 205.788017; ...</td>
      </tr>
      <tr>
          <td>PURCHASES_FREQUENCY</td>
          <td>Frequency of purchases made on a regular basis (between 0 and 1)<br><br>1 = frequently purchased<br>0 = not frequently purchased</td>
          <td>0.166667; 0.083333; ...</td>
      </tr>
      <tr>
          <td>ONEOFF_PURCHASES_FREQUENCY</td>
          <td>Frequency of purchases made in single transaction (between 0 and 1)<br><br>1 = frequently purchased<br>0 = not frequently purchased</td>
          <td>0.083333; 0.083333; ...</td>
      </tr>
      <tr>
          <td>PURCHASES_INSTALLMENTS_FREQUENCY</td>
          <td>Frequency of done purchases in installments (between 0 and 1)<br><br>1 = frequently done<br>0 = not frequently done</td>
          <td>0.083333; 0.583333; ...</td>
      </tr>
      <tr>
          <td>CASH_ADVANCE_FREQUENCY</td>
          <td>Frequency of cash in advance</td>
          <td>0.25; 0.083333; ...</td>
      </tr>
      <tr>
          <td>CASH_ADVANCE_TRX</td>
          <td>"Cash in advance" total transactions</td>
          <td>0; 4; ...</td>
      </tr>
      <tr>
          <td>PURCHASES_TRX</td>
          <td>Purchase total transactions</td>
          <td>2; 12; ...</td>
      </tr>
      <tr>
          <td>CREDIT_LIMIT</td>
          <td>Credit card limit of an user</td>
          <td>1000; 7000; ...</td>
      </tr>
      <tr>
          <td>PAYMENTS</td>
          <td>Total amount paid by the user</td>
          <td>201.802084; 4103.032597; ...</td>
      </tr>
      <tr>
          <td>MINIMUM_PAYMENTS</td>
          <td>Minimum payment amount made by user</td>
          <td>139.509787; 1072.340217; ...</td>
      </tr>
      <tr>
          <td>PRC_FULL_PAYMENT</td>
          <td>Percent of total charge paid by the user</td>
          <td>0; 0.222222; ...</td>
      </tr>
      <tr>
          <td>TENURE</td>
          <td>Credit card tenure of an user</td>
          <td>12; 8; ...</td>
      </tr>
  </tbody>
</table>
    
</div>

# <div class="header1">2. | Reading Dataset </div>
<div class="explain-box">
    Import the data set from your drive</b>.
</div>

In [ ]:
#céer une connection avec google colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import all needed librairies
# --- Importing Libraries ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import scipy.cluster.hierarchy as shc
from sklearn.neighbors import NearestNeighbors
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import davies_bouldin_score, silhouette_score, calinski_harabasz_score
from yellowbrick.cluster import KElbowVisualizer, SilhouetteVisualizer

In [ ]:
#import the data set
# --- Importing Dataset ---
df = pd.read_csv('/content/drive/MyDrive/Data/CC GENERAL.csv')

In [ ]:
df.head()

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12

# <div class="header1">3. | Initial Dataset Exploration 🔍</div>
<div class="explain-box">
    This section will focused on initial data exploration on the dataset before pre-processing performed. In addition, <b>variables correlation</b> will be examined as well.
</div>

In [ ]:
df.describe()

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
count,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8949.000000,8950.000000,8637.000000,8950.000000,8950.000000
mean,1564.474828,0.877271,1003.204834,592.437371,411.067645,978.871112,0.490351,0.202458,0.364437,0.135144,3.248827,14.709832,4494.449450,1733.143852,864.206542,0.153715,11.517318
std,2081.531879,0.236904,2136.634782,1659.887917,904.338115,2097.163877,0.401371,0.298336,0.397448,0.200121,6.824647,24.857649,3638.815725,2895.063757,2372.446607,0.292499,1.338331
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.019163,0.000000,6.000000
25%,128.281915,0.888889,39.635000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,1.000000,1600.000000,383.276166,169.123707,0.000000,12.000000
50%,873.385231,1.000000,361.280000,38.000000,89.000000,0.000000,0.500000,0.083333,0.166667,0.000000,0.000000,7.000000,3000.000000,856.901546,312.343947,0.000000,12.000000
75%,2054.140036,1.000000,1110.130000,577.405000,468.637500,1113.821139,0.916667,0.300000,0.750000,0.222222,4.000000,17.000000,6500.000000,1901.134317,825.485459,0.142857,12.000000
max,19043.138560,1.000000,49039.570000,40761.250000,22500.000000,47137.211760,1.000000,1.000000,1.000000,1.500000,123.000000,358.000000,30000.000000,50721.483360,76406.207520,1.000000,12.000000

# <div class="header1">4. | Preprocessing </div>
<div class="explain-box">
    This section will perform some <mark><b>data pre-processing</b></mark> before using clustering models.
</div>

## <div class="header2">4.1 | Dropping Variables </div>
<div class="explain-box">
    The first stage is to remove variables that are not needed for the clustering process. In this case, <b>CUST_ID will be removed</b> since it has unique values.
</div>

## <div class="header2">4.2 | Imputation </div>
<div class="explain-box">
    Since the dataset is about clustering, imputation will use <code>KNNImputer()</code> to <mark><b>avoid biased clustering results</b></mark>. The <b>mean value from the nearest</b> <code>n_neighbors</code> found in the dataset is used to impute the missing values for each sample.
</div>

## <div class="header2">4.3 | Scaling </div>
<div class="explain-box">
    The next step is <mark><b>scaling</b></mark> the dataset. Scaling is essential since it manages the <b>dataset's variability</b>, <b>transforms data into a defined range</b> using a linear transformation to produce high-quality clusters, and <b>boosts the precision of clustering algorithms</b>. In this case, a <mark><b>standard scaler</b></mark> used to <b>standardizes the feature by removing the mean and scaling to unit variance</b>.
</div>

## <div class="header2">4.4 | PCA </div>
<div class="explain-box">
    <b>Principal component analysis (PCA)</b> is a method used in unsupervised machine learning that <b>reduces high-dimension data to smaller dimensions while preserving as much information as possible</b>. By using PCA before applying clustering algorithm, it allows to <b>reduces dimensions, data noise, and decrease computation cost</b>. In this notebook, the number of features will be reduced to 2 dimensions so that the clustering results can be visualized.
</div>

# <div class="header1">5. | Clustering Models ⚙</div>
<div class="explain-box">
    This section will <b>implement clustering techniques</b> as mentioned in the first section.
</div>
<div class="explain-box">
    The <b>clustering models</b> to implement:
    <ol>
        <li><b>Partition based (K-Means)</b>,</li>
        <li><b>Density based (DBSCAN)</b>, and</li>
        <li><b>Hierarchical Clustering (Agglomerative)</b>.</li>
    </ol>
</div>

# <div class="header2">6 | Models Evaluation</div>
<div class="explain-box">
    In this section, <b>an evaluation of the quality of the clustering results</b> will be carried out. The objective is to compare  clustering results using Davies-Bouldin index, silhouette score and the Calinski Harabasz index.
    </div>

# <div class="header2">7 | Conclusion</div>